name: Test deployment

on:
  push:
    branches: [new-website]
    paths: [./**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: npm
      - name: Test build
        working-directory: ./
        run: |
          npm ci
          npm run build
